variants_begins_with = [
    "filtrado por {object} que empieza con {value}",
    "condicionado a {object} que empieza con {value}",
    "restringido a {object} que empieza con {value}",
    "limitado a {object} que empieza con {value}",
    "filtrado por {object} cuyo valor empieza con {value}",
    "condicionado a {object} cuyo valor empieza con {value}",
    "restringido a {object} cuyo valor empieza con {value}",
    "limitado a {object} cuyo valor empieza con {value}",
    "con {object} que empieza con {value}",
    "que tenga {object} que empieza con {value}",
    "que sea {object} que empieza con {value}",
    "con {object} que comience con {value}",
    "con {object} que tenga un valor que comience con {value}",
    "de {object} que empieza con {value}",
    "de {object} que comience con {value}",
    "filtrado por {object} que comience con {value}",
    "condicionado a {object} que comience con {value}",
    "restringido a {object} que comience con {value}",
    "limitado a {object} que comience con {value}",
    "con {object} cuyo valor comienza con {value}",
    "filtrado por {object} cuyo valor comienza con {value}",
    "condicionado a {object} cuyo valor comienza con {value}",
    "restringido a {object} cuyo valor comienza con {value}",
    "limitado a {object} cuyo valor comienza con {value}",
    "comienza con {object} {value}",
    "comienza con {object} en {value}",
    "comienza con {object} dentro de {value}",
    "donde {object} comienza con {value}",
    "donde {object} empieza con {value}",
    "donde {object} inicia con {value}",
    "donde {object} empieza por {value}",
    "donde {object} arranca con {value}",
    "de {object} cuyo valor inicia con {value}",
    "de {object} cuyo valor empieza con {value}",
    "de {object} cuyo valor comienza con {value}",
]
