countries = [
    {"United States": "Estados Unidos"},
    {"Spain": "España"},
    {"France": "Francia"},
    {"Germany": "Alemania"},
    {"Italy": "Italia"},
    {"United Kingdom": "Reino Unido"},
    {"Canada": "Canadá"},
    {"Mexico": "México"},
    {"Brazil": "Brasil"},
    {"Argentina": "Argentina"},
    {"Chile": "Chile"},
    {"Colombia": "Colombia"},
    {"Peru": "Perú"},
    {"Venezuela": "Venezuela"},
    {"Uruguay": "Uruguay"},
    {"Paraguay": "Paraguay"},
    {"Bolivia": "Bolivia"},
    {"Ecuador": "Ecuador"},
    {"Panama": "Panamá"},
    {"Costa Rica": "Costa Rica"},
    {"Guatemala": "Guatemala"},
    {"Honduras": "Honduras"},
    {"El Salvador": "El Salvador"},
    {"Nicaragua": "Nicaragua"},
    {"Dominican Republic": "República Dominicana"},
    {"Cuba": "Cuba"},
    {"Puerto Rico": "Puerto Rico"},
    {"Portugal": "Portugal"},
    {"Sweden": "Suecia"},
    {"Norway": "Noruega"},
    {"Denmark": "Dinamarca"},
    {"Finland": "Finlandia"},
    {"Russia": "Rusia"},
    {"China": "China"},
    {"Japan": "Japón"},
    {"South Korea": "Corea del Sur"},
    {"India": "India"},
    {"Australia": "Australia"},
    {"New Zealand": "Nueva Zelanda"},
    {"South Africa": "Sudáfrica"},
    {"Egypt": "Egipto"},
    {"Morocco": "Marruecos"},
    {"Algeria": "Argelia"},
    {"Nigeria": "Nigeria"},
    {"Kenya": "Kenia"},
    {"Ghana": "Ghana"},
    {"Turkey": "Turquía"},
    {"Israel": "Israel"},
    {"Saudi Arabia": "Arabia Saudita"},
    {"Austria": "Austria"},
    {"Belgium": "Bélgica"},
    {"Switzerland": "Suiza"},
    {"Netherlands": "Países Bajos"},
    {"Greece": "Grecia"},
    {"Poland": "Polonia"},
    {"Czech Republic": "República Checa"},
    {"Hungary": "Hungría"},
    {"Romania": "Rumanía"},
    {"Bulgaria": "Bulgaria"},
    {"Slovakia": "Eslovaquia"},
    {"Slovenia": "Eslovenia"},
    {"Croatia": "Croacia"},
    {"Bosnia and Herzegovina": "Bosnia y Herzegovina"},
    {"Serbia": "Serbia"},
    {"Montenegro": "Montenegro"},
    {"North Macedonia": "Macedonia del Norte"},
    {"Albania": "Albania"},
    {"Kosovo": "Kosovo"},
    {"Lithuania": "Lituania"},
    {"Latvia": "Letonia"},
    {"Estonia": "Estonia"},
    {"Ukraine": "Ucrania"},
    {"Belarus": "Bielorrusia"},
    {"Moldova": "Moldavia"},
    {"Georgia": "Georgia"},
    {"Armenia": "Armenia"},
    {"Azerbaijan": "Azerbaiyán"},
    {"Kazakhstan": "Kazajistán"},
    {"Uzbekistan": "Uzbekistán"},
    {"Turkmenistan": "Turkmenistán"},
    {"Kyrgyzstan": "Kirguistán"},
    {"Tajikistan": "Tayikistán"},
    {"Mongolia": "Mongolia"},
    {"Vietnam": "Vietnam"},
    {"Thailand": "Tailandia"},
    {"Malaysia": "Malasia"},
    {"Singapore": "Singapur"},
    {"Indonesia": "Indonesia"},
    {"Philippines": "Filipinas"},
    {"Myanmar": "Birmania"},
    {"Sri Lanka": "Sri Lanka"},
    {"Bangladesh": "Bangladés"},
    {"Pakistan": "Pakistán"},
    {"Afghanistan": "Afganistán"},
    {"Nepal": "Nepal"},
    {"Bhutan": "Bután"},
    {"Maldives": "Maldivas"},
    {"Lebanon": "Líbano"},
    {"Jordan": "Jordania"},
    {"Iraq": "Irak"}
]