variants_ends_with = [
    "filtrado por {object} que termina con {value}",
    "condicionado a {object} que termina con {value}",
    "restringido a {object} que termina con {value}",
    "limitado a {object} que termina con {value}",
    "filtrado por {object} cuyo valor termina con {value}",
    "condicionado a {object} cuyo valor termina con {value}",
    "restringido a {object} cuyo valor termina con {value}",
    "limitado a {object} cuyo valor termina con {value}",
    "con {object} que termina con {value}",
    "que tenga {object} que termina con {value}",
    "que sea {object} que termina con {value}",
    "con {object} que acabe con {value}",
    "con {object} que tenga un valor que acabe con {value}",
    "de {object} que termina con {value}",
    "de {object} que acabe con {value}",
    "filtrado por {object} que acabe con {value}",
    "condicionado a {object} que acabe con {value}",
    "restringido a {object} que acabe con {value}",
    "limitado a {object} que acabe con {value}",
    "con {object} cuyo valor acaba con {value}",
    "filtrado por {object} cuyo valor acaba con {value}",
    "condicionado a {object} cuyo valor acaba con {value}",
    "restringido a {object} cuyo valor acaba con {value}",
    "limitado a {object} cuyo valor acaba con {value}",
    "acaba con {object} {value}",
    "acaba con {object} en {value}",
    "acaba con {object} dentro de {value}",
    "donde {object} termina con {value}",
    "donde {object} acaba con {value}",
    "donde {object} concluye con {value}",
    "donde {object} finaliza con {value}",
    "de {object} cuyo valor concluye con {value}",
    "de {object} cuyo valor termina con {value}",
    "de {object} cuyo valor finaliza con {value}",
]
