variants_greater_than_or_equal_to = [
    "filtrado por {object} mayor o igual que {value}",
    "condicionado a {object} mayor o igual que {value}",
    "restringido a {object} mayor o igual que {value}",
    "limitado a {object} mayor o igual que {value}",
    "filtrado por {object} cuyo valor sea mayor o igual que {value}",
    "condicionado a {object} cuyo valor sea mayor o igual que {value}",
    "restringido a {object} cuyo valor sea mayor o igual que {value}",
    "limitado a {object} cuyo valor sea mayor o igual que {value}",
    "con {object} mayor o igual que {value}",
    "que tenga {object} mayor o igual que {value}",
    "que sea {object} mayor o igual que {value}",
    "con {object} que sea mayor o igual que {value}",
    "con {object} que tenga un valor mayor o igual que {value}",
    "de {object} mayor o igual que {value}",
    "de {object} que sea mayor o igual que {value}",
    "filtrado por {object} que sea mayor o igual que {value}",
    "condicionado a {object} que sea mayor o igual que {value}",
    "restringido a {object} que sea mayor o igual que {value}",
    "limitado a {object} que sea mayor o igual que {value}",
    "con {object} cuyo valor sea mayor o igual que {value}",
    "filtrado por {object} cuyo valor sea mayor o igual que {value}",
    "condicionado a {object} cuyo valor sea mayor o igual que {value}",
    "restringido a {object} cuyo valor sea mayor o igual que {value}",
    "limitado a {object} cuyo valor sea mayor o igual que {value}",
    "mayor o igual que {object} {value}",
    "mayor o igual que {object} en {value}",
    "mayor o igual que {object} dentro de {value}",
    "donde {object} sea mayor o igual que {value}",
    "donde {object} es mayor o igual que {value}",
    "donde {object} cumple o excede {value}",
    "donde {object} alcanza o supera {value}",
    "de {object} cuyo valor cumple o excede {value}",
    "de {object} cuyo valor es mayor o igual que {value}",
    "de {object} cuyo valor alcanza o supera {value}",
]
