variants_less_than = [
    "filtrado por {object} menor que {value}",
    "condicionado a {object} menor que {value}",
    "restringido a {object} menor que {value}",
    "limitado a {object} menor que {value}",
    "filtrado por {object} cuyo valor sea menor que {value}",
    "condicionado a {object} cuyo valor sea menor que {value}",
    "restringido a {object} cuyo valor sea menor que {value}",
    "limitado a {object} cuyo valor sea menor que {value}",
    "con {object} menor que {value}",
    "que tenga {object} menor que {value}",
    "que sea {object} menor que {value}",
    "con {object} que sea menor que {value}",
    "con {object} que tenga un valor menor que {value}",
    "de {object} menor que {value}",
    "de {object} que sea menor que {value}",
    "filtrado por {object} que sea menor que {value}",
    "condicionado a {object} que sea menor que {value}",
    "restringido a {object} que sea menor que {value}",
    "limitado a {object} que sea menor que {value}",
    "con {object} cuyo valor sea menor que {value}",
    "filtrado por {object} cuyo valor sea menor que {value}",
    "condicionado a {object} cuyo valor sea menor que {value}",
    "restringido a {object} cuyo valor sea menor que {value}",
    "limitado a {object} cuyo valor sea menor que {value}",
    "menor que {object} {value}",
    "menor que {object} en {value}",
    "menor que {object} dentro de {value}",
    "donde {object} sea menor que {value}",
    "donde {object} es menor que {value}",
    "donde {object} no alcanza {value}",
    "donde {object} está por debajo de {value}",
    "de {object} cuyo valor no alcanza {value}",
    "de {object} cuyo valor es menor que {value}",
    "de {object} cuyo valor está por debajo de {value}",
]
