cities = [
    {"New York": "Nueva York"},
    {"Los Angeles": "Los Ángeles"},
    {"Chicago": "Chicago"},
    {"Houston": "Houston"},
    {"Miami": "Miami"},
    {"Madrid": "Madrid"},
    {"Barcelona": "Barcelona"},
    {"Paris": "París"},
    {"Berlin": "Berlín"},
    {"Rome": "Roma"},
    {"London": "Londres"},
    {"Tokyo": "Tokio"},
    {"Beijing": "Pekín"},
    {"Shanghai": "Shanghái"},
    {"Moscow": "Moscú"},
    {"Dubai": "Dubái"},
    {"Sydney": "Sídney"},
    {"Melbourne": "Melbourne"},
    {"Buenos Aires": "Buenos Aires"},
    {"Mexico City": "Ciudad de México"},
    {"São Paulo": "São Paulo"},
    {"Rio de Janeiro": "Río de Janeiro"},
    {"Lima": "Lima"},
    {"Bogotá": "Bogotá"},
    {"Santiago": "Santiago"},
    {"Caracas": "Caracas"},
    {"Lisbon": "Lisboa"},
    {"Amsterdam": "Ámsterdam"},
    {"Brussels": "Bruselas"},
    {"Vienna": "Viena"},
    {"Warsaw": "Varsovia"},
    {"Prague": "Praga"},
    {"Budapest": "Budapest"},
    {"Athens": "Atenas"},
    {"Istanbul": "Estambul"},
    {"Cairo": "El Cairo"},
    {"Johannesburg": "Johannesburgo"},
    {"Cape Town": "Ciudad del Cabo"},
    {"Bangkok": "Bangkok"},
    {"Seoul": "Seúl"},
    {"Hong Kong": "Hong Kong"},
    {"Singapore": "Singapur"},
    {"Kuala Lumpur": "Kuala Lumpur"},
    {"Jakarta": "Yakarta"},
    {"Manila": "Manila"},
    {"Hanoi": "Hanói"},
    {"Delhi": "Delhi"},
    {"Mumbai": "Bombay"},
    {"Bangalore": "Bangalore"},
    {"Chennai": "Chennai"},
    {"Milan": "Milán"},
    {"Zurich": "Zúrich"},
    {"Geneva": "Ginebra"},
    {"Vienna": "Viena"},
    {"Stockholm": "Estocolmo"},
    {"Copenhagen": "Copenhague"},
    {"Oslo": "Oslo"},
    {"Helsinki": "Helsinki"},
    {"Dublin": "Dublín"},
    {"Bratislava": "Bratislava"},
    {"Ljubljana": "Liubliana"},
    {"Sofia": "Sofía"},
    {"Bucharest": "Bucarest"},
    {"Kiev": "Kiev"},
    {"Minsk": "Minsk"},
    {"St. Petersburg": "San Petersburgo"},
    {"Almaty": "Almatý"},
    {"Astana": "Astaná"},
    {"Tashkent": "Taskent"},
    {"Baku": "Bakú"},
    {"Tbilisi": "Tiflis"},
    {"Yerevan": "Ereván"},
    {"Tehran": "Teherán"},
    {"Baghdad": "Bagdad"},
    {"Damascus": "Damasco"},
    {"Riyadh": "Riad"},
    {"Jeddah": "Yeda"},
    {"Mecca": "La Meca"},
    {"Medina": "Medina"},
    {"Kuwait City": "Ciudad de Kuwait"},
    {"Doha": "Doha"},
    {"Abu Dhabi": "Abu Dabi"},
    {"Kabul": "Kabul"},
    {"Islamabad": "Islamabad"},
    {"Karachi": "Karachi"},
    {"Lahore": "Lahore"},
    {"Dhaka": "Daca"},
    {"Yangon": "Rangún"},
    {"Phnom Penh": "Nom Pen"},
    {"Ho Chi Minh City": "Ciudad Ho Chi Minh"},
    {"Taipei": "Taipéi"},
    {"Managua": "Managua"},
    {"San Salvador": "San Salvador"},
    {"Guatemala City": "Ciudad de Guatemala"},
    {"Tegucigalpa": "Tegucigalpa"},
    {"San José": "San José"},
    {"Panama City": "Ciudad de Panamá"}
]
