countries = [
    {"English": "United States", "Spanish": "Estados Unidos"},
    {"English": "Spain", "Spanish": "España"},
    {"English": "France", "Spanish": "Francia"},
    {"English": "Germany", "Spanish": "Alemania"},
    {"English": "Italy", "Spanish": "Italia"},
    {"English": "United Kingdom", "Spanish": "Reino Unido"},
    {"English": "Canada", "Spanish": "Canadá"},
    {"English": "Mexico", "Spanish": "México"},
    {"English": "Brazil", "Spanish": "Brasil"},
    {"English": "Argentina", "Spanish": "Argentina"},
    {"English": "Chile", "Spanish": "Chile"},
    {"English": "Colombia", "Spanish": "Colombia"},
    {"English": "Peru", "Spanish": "Perú"},
    {"English": "Venezuela", "Spanish": "Venezuela"},
    {"English": "Uruguay", "Spanish": "Uruguay"},
    {"English": "Paraguay", "Spanish": "Paraguay"},
    {"English": "Bolivia", "Spanish": "Bolivia"},
    {"English": "Ecuador", "Spanish": "Ecuador"},
    {"English": "Panama", "Spanish": "Panamá"},
    {"English": "Costa Rica", "Spanish": "Costa Rica"},
    {"English": "Guatemala", "Spanish": "Guatemala"},
    {"English": "Honduras", "Spanish": "Honduras"},
    {"English": "El Salvador", "Spanish": "El Salvador"},
    {"English": "Nicaragua", "Spanish": "Nicaragua"},
    {"English": "Dominican Republic", "Spanish": "República Dominicana"},
    {"English": "Cuba", "Spanish": "Cuba"},
    {"English": "Puerto Rico", "Spanish": "Puerto Rico"},
    {"English": "Portugal", "Spanish": "Portugal"},
    {"English": "Sweden", "Spanish": "Suecia"},
    {"English": "Norway", "Spanish": "Noruega"},
    {"English": "Denmark", "Spanish": "Dinamarca"},
    {"English": "Finland", "Spanish": "Finlandia"},
    {"English": "Russia", "Spanish": "Rusia"},
    {"English": "China", "Spanish": "China"},
    {"English": "Japan", "Spanish": "Japón"},
    {"English": "South Korea", "Spanish": "Corea del Sur"},
    {"English": "India", "Spanish": "India"},
    {"English": "Australia", "Spanish": "Australia"},
    {"English": "New Zealand", "Spanish": "Nueva Zelanda"},
    {"English": "South Africa", "Spanish": "Sudáfrica"},
    {"English": "Egypt", "Spanish": "Egipto"},
    {"English": "Morocco", "Spanish": "Marruecos"},
    {"English": "Algeria", "Spanish": "Argelia"},
    {"English": "Nigeria", "Spanish": "Nigeria"},
    {"English": "Kenya", "Spanish": "Kenia"},
    {"English": "Ghana", "Spanish": "Ghana"},
    {"English": "Turkey", "Spanish": "Turquía"},
    {"English": "Israel", "Spanish": "Israel"},
    {"English": "Saudi Arabia", "Spanish": "Arabia Saudita"},
    {"English": "Austria", "Spanish": "Austria"},
    {"English": "Belgium", "Spanish": "Bélgica"},
    {"English": "Switzerland", "Spanish": "Suiza"},
    {"English": "Netherlands", "Spanish": "Países Bajos"},
    {"English": "Greece", "Spanish": "Grecia"},
    {"English": "Poland", "Spanish": "Polonia"},
    {"English": "Czech Republic", "Spanish": "República Checa"},
    {"English": "Hungary", "Spanish": "Hungría"},
    {"English": "Romania", "Spanish": "Rumanía"},
    {"English": "Bulgaria", "Spanish": "Bulgaria"},
    {"English": "Slovakia", "Spanish": "Eslovaquia"},
    {"English": "Slovenia", "Spanish": "Eslovenia"},
    {"English": "Croatia", "Spanish": "Croacia"},
    {"English": "Bosnia and Herzegovina", "Spanish": "Bosnia y Herzegovina"},
    {"English": "Serbia", "Spanish": "Serbia"},
    {"English": "Montenegro", "Spanish": "Montenegro"},
    {"English": "North Macedonia", "Spanish": "Macedonia del Norte"},
    {"English": "Albania", "Spanish": "Albania"},
    {"English": "Kosovo", "Spanish": "Kosovo"},
    {"English": "Lithuania", "Spanish": "Lituania"},
    {"English": "Latvia", "Spanish": "Letonia"},
    {"English": "Estonia", "Spanish": "Estonia"},
    {"English": "Ukraine", "Spanish": "Ucrania"},
    {"English": "Belarus", "Spanish": "Bielorrusia"},
    {"English": "Moldova", "Spanish": "Moldavia"},
    {"English": "Georgia", "Spanish": "Georgia"},
    {"English": "Armenia", "Spanish": "Armenia"},
    {"English": "Azerbaijan", "Spanish": "Azerbaiyán"},
    {"English": "Kazakhstan", "Spanish": "Kazajistán"},
    {"English": "Uzbekistan", "Spanish": "Uzbekistán"},
    {"English": "Turkmenistan", "Spanish": "Turkmenistán"},
    {"English": "Kyrgyzstan", "Spanish": "Kirguistán"},
    {"English": "Tajikistan", "Spanish": "Tayikistán"},
    {"English": "Mongolia", "Spanish": "Mongolia"},
    {"English": "Vietnam", "Spanish": "Vietnam"},
    {"English": "Thailand", "Spanish": "Tailandia"},
    {"English": "Malaysia", "Spanish": "Malasia"},
    {"English": "Singapore", "Spanish": "Singapur"},
    {"English": "Indonesia", "Spanish": "Indonesia"},
    {"English": "Philippines", "Spanish": "Filipinas"},
    {"English": "Myanmar", "Spanish": "Birmania"},
    {"English": "Sri Lanka", "Spanish": "Sri Lanka"},
    {"English": "Bangladesh", "Spanish": "Bangladés"},
    {"English": "Pakistan", "Spanish": "Pakistán"},
    {"English": "Afghanistan", "Spanish": "Afganistán"},
    {"English": "Nepal", "Spanish": "Nepal"},
    {"English": "Bhutan", "Spanish": "Bután"},
    {"English": "Maldives", "Spanish": "Maldivas"},
    {"English": "Lebanon", "Spanish": "Líbano"},
    {"English": "Jordan", "Spanish": "Jordania"},
    {"English": "Iraq", "Spanish": "Irak"}
]