variants = [
        "filtrado por {object} igual a {value}",
        "condicionado a {object} igual a {value}",
        "restringido a {object} igual a {value}",
        "limitado a {object} igual a {value}",
        "filtrado por {object} que sea igual a {value}",
        "condicionado a {object} que sea igual a {value}",
        "restringido a {object} que sea igual a {value}",
        "limitado a {object} que sea igual a {value}",
        "filtrado por {object} que sea {value}",
        "condicionado a {object} que sea {value}",
        "restringido a {object} que sea {value}",
        "limitado a {object} que sea {value}",
        "filtrado por {object} que tenga el valor de {value}",
        "condicionado a {object} que tenga el valor de {value}",
        "restringido a {object} que tenga el valor de {value}",
        "limitado a {object} que tenga el valor de {value}",
        "con {object} igual a {value}",
        "que tenga {object} igual a {value}",
        "que sea {object} {value}",
        "con {object} que sea igual a {value}",
        "con {object} que sea {value}",
        "que tenga {object} con el valor de {value}",
        "de {object} igual a {value}",
        "de {object} que sea igual a {value}",
        "filtrado por {object} con {value}",
        "condicionado a {object} con {value}",
        "restringido a {object} con {value}",
        "limitado a {object} con {value}",
        "filtrado por {object} que tengan {value}",
        "condicionado a {object} que tengan {value}",
        "restringido a {object} que tengan {value}",
        "limitado a {object} que tengan {value}",
        "filtrado por {object} que coincida con {value}",
        "condicionado a {object} que coincida con {value}",
        "restringido a {object} que coincida con {value}",
        "limitado a {object} que coincida con {value}",
        "filtrado por {object} equivalente a {value}",
        "condicionado a {object} equivalente a {value}",
        "restringido a {object} equivalente a {value}",
        "limitado a {object} equivalente a {value}",
        "con {object} equivalente a {value}",
        "filtrado por {object} cuyo valor sea {value}",
        "condicionado a {object} cuyo valor sea {value}",
        "restringido a {object} cuyo valor sea {value}",
        "limitado a {object} cuyo valor sea {value}",
        "con {object} cuyo valor sea {value}",
        "de {object} cuyo valor sea {value}",
        "con {object} que tenga un valor de {value}",
        "filtrado por {object} que tenga un valor de {value}",
        "condicionado a {object} que tenga un valor de {value}",
        "restringido a {object} que tenga un valor de {value}",
        "limitado a {object} que tenga un valor de {value}",
        "igual a {object} {value}",
        "igual a {object} en {value}",
        "igual a {object} dentro de {value}",
        "donde {object} es igual a {value}",
        "donde {object} coincide con {value}",
        "donde {object} equivale a {value}"
    ]