variants_greater_than = [
    "filtrado por {object} mayor que {value}",
    "condicionado a {object} mayor que {value}",
    "restringido a {object} mayor que {value}",
    "limitado a {object} mayor que {value}",
    "filtrado por {object} cuyo valor sea mayor que {value}",
    "condicionado a {object} cuyo valor sea mayor que {value}",
    "restringido a {object} cuyo valor sea mayor que {value}",
    "limitado a {object} cuyo valor sea mayor que {value}",
    "con {object} mayor que {value}",
    "que tenga {object} mayor que {value}",
    "que sea {object} mayor que {value}",
    "con {object} que sea mayor que {value}",
    "con {object} que tenga un valor mayor que {value}",
    "de {object} mayor que {value}",
    "de {object} que sea mayor que {value}",
    "filtrado por {object} que sea mayor que {value}",
    "condicionado a {object} que sea mayor que {value}",
    "restringido a {object} que sea mayor que {value}",
    "limitado a {object} que sea mayor que {value}",
    "con {object} cuyo valor sea mayor que {value}",
    "filtrado por {object} cuyo valor sea mayor que {value}",
    "condicionado a {object} cuyo valor sea mayor que {value}",
    "restringido a {object} cuyo valor sea mayor que {value}",
    "limitado a {object} cuyo valor sea mayor que {value}",
    "mayor que {object} {value}",
    "mayor que {object} en {value}",
    "mayor que {object} dentro de {value}",
    "donde {object} sea mayor que {value}",
    "donde {object} es mayor que {value}",
    "donde {object} supera {value}",
    "donde {object} excede {value}",
    "de {object} cuyo valor supera {value}",
    "de {object} cuyo valor es mayor que {value}",
    "de {object} cuyo valor excede {value}",
]
