variants_less_than_or_equal_to = [
    "filtrado por {object} menor o igual que {value}",
    "condicionado a {object} menor o igual que {value}",
    "restringido a {object} menor o igual que {value}",
    "limitado a {object} menor o igual que {value}",
    "filtrado por {object} cuyo valor sea menor o igual que {value}",
    "condicionado a {object} cuyo valor sea menor o igual que {value}",
    "restringido a {object} cuyo valor sea menor o igual que {value}",
    "limitado a {object} cuyo valor sea menor o igual que {value}",
    "con {object} menor o igual que {value}",
    "que tenga {object} menor o igual que {value}",
    "que sea {object} menor o igual que {value}",
    "con {object} que sea menor o igual que {value}",
    "con {object} que tenga un valor menor o igual que {value}",
    "de {object} menor o igual que {value}",
    "de {object} que sea menor o igual que {value}",
    "filtrado por {object} que sea menor o igual que {value}",
    "condicionado a {object} que sea menor o igual que {value}",
    "restringido a {object} que sea menor o igual que {value}",
    "limitado a {object} que sea menor o igual que {value}",
    "con {object} cuyo valor sea menor o igual que {value}",
    "filtrado por {object} cuyo valor sea menor o igual que {value}",
    "condicionado a {object} cuyo valor sea menor o igual que {value}",
    "restringido a {object} cuyo valor sea menor o igual que {value}",
    "limitado a {object} cuyo valor sea menor o igual que {value}",
    "menor o igual que {object} {value}",
    "menor o igual que {object} en {value}",
    "menor o igual que {object} dentro de {value}",
    "donde {object} sea menor o igual que {value}",
    "donde {object} es menor o igual que {value}",
    "donde {object} no supera {value}",
    "donde {object} está por debajo o igual a {value}",
    "de {object} cuyo valor no supera {value}",
    "de {object} cuyo valor es menor o igual que {value}",
    "de {object} cuyo valor está por debajo o igual a {value}",
]
